#### general settings
name: DDBPN_TEST_EXP_01
use_visdom: false
visdom_port: 8067
model: cnn
device: cuda

#### datasets
dataset:
  scale: 2
  train:
    scale: 2
    mode: LRHR
    dataroot_HR: data/datasets/DIV2Kx2/hr/train
    dataroot_LR: data/datasets/DIV2Kx2/lr/train
    data_type: npy
    n_workers: 4
    batch_size: 20
    LR_size: 32
    use_flip: true
    use_rot: true
    noise: .
  test:
    scale: 2
    mode: LRHR
    dataroot_HR: data/datasets/Set5x2/hr/test
    dataroot_LR: data/datasets/Set5x2/lr/test
    data_type: img 

#### network structures
network_G:
  model: DDBPN
  num_features: 64
  in_channels: 3
  out_channels: 3
  num_blocks: 7

#### training settings: learning rate scheme, loss
train:
  epoch: 1000

  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99

  lr_step: 10
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e0

  manual_seed: 10
  val_freq: 1 # epoch

#### logger
logger:
  print_freq: 50 # iter
  path: experiments/
  chkpt_freq: 2 # epoch
  