#### general settings
name: GAN_TEST_01
use_visdom: true
visdom_port: 8067
model: gan
device: cuda

#### datasets
dataset:
  scale: 2
  train:
    name: BSDS300
    data_location: data/datasets/BSDS300/train/
    shuffle: true
    n_workers: 6  # per GPU
    batch_size: 5
    lr_size: 128
    repeat: 2
  test:
    name: BSDS300
    data_location: data/datasets/BSDS300/test/
    shuffle: false
    n_workers: 1  # per GPU
    batch_size: 1
    repeat: 1

#### network structures
network_G:
  model: SRResNet
  layers: 16

network_D:
  model: LeakyVGG
  in_nc: 3
  nf: 64
#### training settings: learning rate scheme, loss
train:
  epoch: 100

  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99

  lr_step: 10
  lr_gamma: 0.5

  pixel_criterion: l2
  pixel_weight: !!float 1e0
  feature_criterion: l2
  feature_weight: !!float 6e-3
  adversarial_criterion: BCEL
  gan_type: gan  # gan | ragan
  gan_weight: !!float 1e-3
  feature_extractor: vgg19

  real_weightD: 0.5
  fake_weightD: 0.5

  manual_seed: 10
  val_freq: 6 # epoch

#### logger
logger:
  print_freq: 5 # epoch
  path: experiments/
  chkpt_freq: 2 # epoch
  