#### general settings
name: GAN_TEST_01
is_train: true
use_visdom: true
visdom_port: 8067
model: gan
device: cuda

#### datasets
dataset:
  scale: 2
  train:
    name: BSDS300
    data_location: data/datasets/BSDS300/train/
    shuffle: true
    n_workers: 1  # per GPU
    batch_size: 16
    lr_size: 32
    repeat: 2
  test:
    name: Set5
    data_location: data/datasets/Set5/test/
    shuffle: false
    n_workers: 1  # per GPU
    batch_size: 1
    repeat: 1

#### network structures
network_G:
  model: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23

network_D:
  model: discriminator_vgg_128
  in_nc: 3
  nf: 64
#### training settings: learning rate scheme, loss
train:
  epoch: 100

  cl_train: false
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99

  lr_scheme: MultiStepLR
  lr_step: [200, 400, 600, 800]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: !!float 1
  adversarial_criterion: BCEL
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3
  feature_extractor: vgg19

  real_weightD: 0.5
  fake_weightD: 0.5

  manual_seed: 10
  val_freq: 5 # epoch

#### logger
logger:
  print_freq: 6 # epoch
  path: experiments/
  chkpt_freq: 2 # epoch
  