#### general settings
name: 0001_RDACN_EXP_01_FSRCNN
is_train: true
use_visdom: false
visdom_port: 8067
model: cnn
device: cuda

#### datasets
dataset:
  scale: 2
  train:
    name: DIV2K
    data_location: data/datasets/DIV2K/train/
    shuffle: true
    n_workers: 0  # per GPU
    batch_size: 20
    lr_size: 40
    repeat: 1
  test:
    name: Set5
    data_location: data/datasets/Set5/test/
    shuffle: false
    n_workers: 1  # per GPU
    batch_size: 1
    repeat: 1

#### network structures
network_G:
  model: RDCAN
  num_features: 32
  in_channels: 3
  out_channels: 3
  num_steps: 8 # later use
  num_groups: 3
  reduction: 8

#### training settings: learning rate scheme, loss
train:
  epoch: 100

  cl_train: false
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99

  lr_scheme: MultiStepLR
  lr_step: [200, 400, 600, 800]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e0

  manual_seed: 10
  val_freq: 5 # epoch

#### logger
logger:
  print_freq: 5 # epoch
  path: experiments/
  chkpt_freq: 2 # epoch
  