#### general settings
name: _0001_SPBPGAN_smallG
is_train: true
use_visdom: false
visdom_port: 8067
model: gan
device: cuda:0

#### datasets
dataset:
  read: ram # disk
  scale: 2
  train:
    name: DIV2K
    data_location: data/datasets/DIV2K/
    shuffle: true
    n_workers: 1  # per GPU
    batch_size: 32
    lr_size: 64
    repeat: 2
  test:
    name: Set5
    data_location: data/datasets/Set5/
    shuffle: false
    n_workers: 1  # per GPU
    batch_size: 1
    repeat: 1

#### network structures
network_G:
  model: SPBP
  num_features: 16
  in_channels: 3
  out_channels: 3
  num_steps: 1
  num_groups: 1

network_D:
  model: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### training settings: learning rate scheme, loss
train:
  epoch: 1000

  cl_train: false
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99

  lr_scheme: MultiStepLR
  lr_step: [200, 400, 600, 800]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: !!float 1
  adversarial_criterion: BCEL
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3
  feature_extractor: vgg19

  real_weightD: 1
  fake_weightD: 1

  manual_seed: 10
  val_freq: 5 # epoch

#### logger
logger:
logger:
  print_freq: 6 # epoch
  chkpt_freq: 100 # epoch
  img_freq: 100
  path: experiments/

path:
  pretrain_model_G: trained_models/1000_SPBP_x2_netG.pth
