#### general settings
name: _0001_SPBPM_resnet_16_x4_48
is_train: true
use_visdom: false
visdom_port: 8067
model: cnn
device: cuda
use_multi_gpu: true
#### datasets
dataset:
  read: ram # disk
  scale: 2
  train:
    name: DIV2K
    data_location: ../../datasets/srv/vimeo_triplet/sequences/
    shuffle: true
    n_workers: 4  # per GPU
    batch_size: 16
    lr_size: 48
    repeat: 1
  test:
    name: Set14
    data_location: ../../datasets/srv/vimeo_triplet/sequences/
    shuffle: false
    n_workers: 4  # per GPU
    batch_size: 1
    repeat: 1

#### network structures
network_G:
  model: SPBP_resnet
  num_features: 16
  in_channels: 3
  out_channels: 3
  num_steps: 1
  num_groups: 10

#### training settings: learning rate scheme, loss
train:
  epoch: 1000
  cl_train: false
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99

  lr_scheme: None
  lr_step: [200, 400, 600, 800]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e0

  manual_seed: 10
  val_freq: 50 # epoch

#### logger
logger:
  print_freq: 6 # epoch
  chkpt_freq: 5 # epoch
  img_freq: 100 # epoch
  path: experiments/
  
