#### general settings
name: SRGAN_Test_Exp_01
use_visdom: false
visdom_port: 8086
model: gan
device: cuda

#### datasets
dataset:
  scale: 2
  train:
    name: DIV2K
    data_location: data/datasets/DIV2K/train/
    shuffle: true
    n_workers: 6  # per GPU
    batch_size: 32
    lr_size: 128
    repeat: 1
  test:
    name: Set5
    data_location: data/datasets/Set5/test/
    shuffle: false
    n_workers: 1  # per GPU
    batch_size: 1
    repeat: 1

#### network structures
network_G:
  model: MSRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 2
network_D:
  model: discriminator_vgg_128
  in_nc: 3
  nf: 64
#### training settings: learning rate scheme, loss
train:
  epoch: 1000

  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99

  lr_step: 10
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  adversarial_criterion: BCEL
  gan_type: gan  # gan | ragan
  gan_weight: !!float 5e-3
  feature_extractor: vgg19

  real_weightD: 1
  fake_weightD: 1

  manual_seed: 10
  val_freq: 1 # epoch

#### logger
logger:
  print_freq: 5 # epoch
  path: experiments/
  chkpt_freq: 10 # epoch
  