#### general settings
name: SRGAN_Test_Exp_01
use_visdom: true
visdom_port: 8086
model: gan
device: cuda

#### datasets
dataset:
  scale: 2
  train:
    name: DIV2K
    mean: [0.4488, 0.4371, 0.404]
    stddev: [0.0039215, 0.0039215, 0.0039215]
    data_location: data/datasets/DIV2K/train/
    shuffle: true
    n_workers: 6  # per GPU
    batch_size: 32
    size: 128
  test:
    name: DIV2K
    mean: [0.4488, 0.4371, 0.404]
    stddev: [0.0039215, 0.0039215, 0.0039215]
    data_location: data/datasets/DIV2K/test/
    shuffle: false
    n_workers: 1  # per GPU
    batch_size: 1
    size: 1000

#### network structures
network_G:
  model: MSRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 2
network_D:
  model: discriminator_vgg_128
  in_nc: 3
  nf: 64
#### training settings: learning rate scheme, loss
train:
  epoch: 1000

  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99

  lr_step: 10
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  adversarial_criterion: BCEL
  gan_type: gan  # gan | ragan
  gan_weight: !!float 5e-3
  feature_extractor: vgg19

  real_weightD: 1
  fake_weightD: 1

  manual_seed: 10
  val_freq: 10 # epoch

#### logger
logger:
  print_freq: 100 # iter
  path: experiments/
  chkpt_freq: 10 # epoch
  