#### general settings
name: SRGAN
model: srgan
device: cuda

#### datasets
dataset:
  scale: 2
  train:
    name: DIV2K
    data_location: data/DIV2K/train/
    shuffle: true
    n_workers: 6  # per GPU
    batch_size: 50
    size: 128
  test:
    name: DIV2K
    data_location: data/DIV2K/test/
    shuffle: false
    n_workers: 1  # per GPU
    batch_size: 1
    size: 1000

#### network structures
network_G:
  model: MSRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 2

network_D:
  model: discriminator_vgg_128
  in_nc: 3
  nf: 64

checkpoint:
  frequency: !!float 1e1
  path: checkpoint/SRGAN/

#### training settings: learning rate scheme, loss
train:
  epoch: 100

  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99

  lr_step: 10
  lr_gamma: 0.5

  content_loss: l2
  content_weight: !!float 1e0
  perceptual_loss: l2
  perceptual_weight: !!float 6e-3
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 1e-3
  feature_extractor: vgg19_bn

  manual_seed: 10
  val_freq: !!float 1e3

#### logger
logger:
  print_freq: 100
  path: experiments/